#define LL_PRESENT_POSITION 132
#define LL_PRESENT_VELOCITY 128
#define LL_PRESENT_CURRENT 126
#define LL_GOAL_CURRENT 102
#define LL_MAX_POSITION 48
#define LL_MIN_POSITION 52
#define LL_GOAL_POSITION  116
#define LL_TORQUE_ENABLE  64
